version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: scripts/stop_wrapper.sh
      timeout: 120
      runas: ec2-user
    - location: scripts/init_wrapper.sh
      timeout: 120
      runas: ec2-user
  ApplicationStart:
    - location: scripts/npm_update_wrapper.sh
      timeout: 120
      runas: ec2-user
    - location: scripts/start_wrapper.sh
      timeout: 120
      runas: ec2-user