version: 0.0
os: linux
#files:
#  - source: Config/config.txt
#    destination: /webapps/Config
#  - source: source
#    destination: /webapps/myApp
hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/npm_update.sh
    - location: scripts/start.sh
      timeout: 3600