version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: scripts/wrapper.sh stop
      timeout: 120
      runas: ec2-user
    - location: scripts/wrapper.sh init
      timeout: 120
      runas: ec2-user
  ApplicationStart:
    - location: scripts/wrapper.sh npm_update
      timeout: 120
      runas: ec2-user
    - location: scripts/wrapper.sh start
      timeout: 120
      runas: ec2-user